### PR TITLE
Theosaurus is now both ST2 and ST3 compatible. Added language selection via settings file.

### LINKED ISSUE #2: not available for sublime text 3?
It seems like I can't install this (great!) package on sublime text 3. My mistake or is that a missing feature?
I'd love to use your package.

### PR DESCRIPTION
**Pull request by git-commit**
Theosaurus can now run on Python 2.7 and Python 3. That means it should be fully compatible with both ST2 and ST3.

I also added a language selector in the settings, so the user can switch easily.

Please test and merge if everything is working :smiley: 

Fixes #2

### CODE REVIEW

**Comment by git-commit** [comment]
Any issues with this? @Nucc

**Comment by Nucc** [comment]
Nope, I'll merge it. Thanks very much!

**Comment by Nucc** [comment]
Is there any configuration change that I should describe in the readme file?

**Comment by git-commit** [comment]
Yep, one can now set the language in the config. Though I modified the default config, this might be worth a mention in the readme. See commit 5d8fea034af53a71e894425b0ce8e4fb8544f125

**Pull request merged**
